apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: draft-api
  name: draft-api
  namespace: draft-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: draft-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: draft-api
    spec:
      containers:
      - image: habor.analytichpxv3.online/kubernetes-workshop/draft-api:v9.9.9 
        name: draft-api
        resources: {}
        ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: dalf-auth
status: {}
